site_name: Notifico
site_url: https://notifico.tech/
repo_url: https://github.com/notificohq/notifico

nav:
  - Overview:
    - index.md
    - components.md
    - Entities:
      - pipeline.md
      - template.md
      - recipient.md
  - quick-start.md
  - Configuration: configuration.md
  - Plugins:
    - Core: plugins/core.md
    - Transports:
      - SMTP (Email): plugins/smtp.md
      - SMPP (SMS): plugins/smpp.md
      - plugins/gotify.md
      - plugins/ntfy.md
      - plugins/pushover.md
      - plugins/slack.md
      - plugins/telegram.md
      - plugins/waba.md
  - API: api.md
  - notificox.md

plugins:
  - swagger-ui-tag
theme:
  name: material
  features:
    - navigation.sections
    - navigation.footer
    - navigation.tabs
  custom_dir: overrides
dev_addr: 127.0.0.1:8080
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: custom