site_name: Notifico
site_url: https://notifico.tech/
repo_url: https://github.com/notificohq/notifico

nav:
  - index.md
  - quick-start.md
  - components.md
  - Configuration: configuration.md
  - Entities:
    - pipeline.md
    - template.md
    - recipient.md
  - API: api.md
  - Plugins and Steps:
      - Core: plugins/core.md
      - SMTP (Email): plugins/smtp.md
      - SMPP (SMS): plugins/smpp.md
      - Telegram: plugins/telegram.md
      - WhatsApp Business: plugins/wa_business.md
      - Slack: plugins/slack.md
      - Pushover: plugins/pushover.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.footer
  custom_dir: overrides
dev_addr: 127.0.0.1:8080
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: custom