site_name: Notifico
site_url: https://notifico.tech/
repo_url: https://github.com/notificohq/notifico

nav:
  - index.md
  - Quick start: quick-start.md
  - Configuration: configuration.md
  - Pipelines: pipelines.md
  - Templates: templates.md
  - API: api.md
  - Channels:
      - SMTP: channels/smtp.md
      - Telegram: channels/telegram.md
      - SMPP (SMS): channels/smpp.md
      - WhatsApp Business: channels/wa_business.md

theme:
  name: material
  features:
    - navigation.sections
  custom_dir: overrides
dev_addr: 127.0.0.1:8001
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: custom