site_name: Notifico
site_url: https://notifico.tech/
repo_url: https://github.com/notificohq/notifico

nav:
  - index.md
  - quick-start.md
  - Pipelines: pipelines.md
  - Configuration: configuration.md
  - Templates: templates.md
  - API: api.md
  - components.md
  - Channels:
      - SMTP (Email): channels/smtp.md
      - SMPP (SMS): channels/smpp.md
      - Telegram: channels/telegram.md
      - WhatsApp Business: channels/wa_business.md
      - Slack: channels/slack.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.footer
  custom_dir: overrides
dev_addr: 127.0.0.1:8001
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: custom